-- 0026: notification dedupe keys (BE-1.34).
--
-- Scheduled notifications (install reminder, hold expiring, feedback invite)
-- are generated by a sweep that runs every few minutes. The key makes each one
-- go out once: the sweep inserts with ON CONFLICT DO NOTHING.
alter table pw_notifications add column if not exists dedupe_key text;
create unique index if not exists pw_notifications_dedupe_uidx
  on pw_notifications (dedupe_key) where dedupe_key is not null;
