import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettierConfig from "eslint-config-prettier";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  prettierConfig,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Tooling that ships with the editor/agent setup — not our source, and it
    // targets CommonJS, which this config deliberately forbids in app code.
    ".claude/**",
    // Generated coverage report (vitest --coverage).
    "coverage/**",
    // Specs and reference prototypes handed to us, kept verbatim so they can be
    // compared against what we built. Not source, never bundled, and linting
    // someone else's single-file prototype to our rules produces only noise.
    "docs/wms-spec/**",
    // Foundry's Solidity dependency libraries (forge-std, OpenZeppelin) —
    // vendored third-party source (including their own JS test suites),
    // never our code, not bundled into the app.
    "contracts/lib/**",
    // Foundry's compiled-artifact output, regenerated by `forge build`.
    "contracts/out/**",
    "contracts/cache/**",
  ]),
]);

export default eslintConfig;
