import { NextResponse } from "next/server";
import { eq } from "drizzle-orm";

import { db } from "@/lib/db/index";
import { coaCertificates, artworks, artistProfiles } from "@/lib/db/schema";

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;

  const [row] = await db
    .select({
      certId: coaCertificates.id,
      hash: coaCertificates.metadataHash,
      status: coaCertificates.status,
      issuedAt: coaCertificates.issuedAt,
      title: artworks.title,
      medium: artworks.medium,
      dimensions: artworks.dimensions,
      year: artworks.year,
      imageUrl: artworks.imageUrl,
      artist: artistProfiles.displayName,
    })
    .from(coaCertificates)
    .innerJoin(artworks, eq(coaCertificates.artworkId, artworks.id))
    .innerJoin(artistProfiles, eq(artworks.userId, artistProfiles.userId))
    .where(eq(coaCertificates.id, id));

  if (!row) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const issued = row.issuedAt
    ? new Date(row.issuedAt).toLocaleDateString("en-IN", {
        year: "numeric",
        month: "long",
        day: "numeric",
      })
    : "—";

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Certificate of Authenticity — ${esc(row.title)}</title>
  <style>
    *{margin:0;padding:0;box-sizing:border-box}
    body{font-family:Georgia,'Times New Roman',serif;max-width:700px;margin:40px auto;padding:40px;border:3px double #222;color:#222}
    .header{text-align:center;border-bottom:1px solid #ccc;padding-bottom:24px;margin-bottom:24px}
    .header h1{font-size:14px;letter-spacing:4px;text-transform:uppercase;color:#666}
    .header h2{font-size:28px;margin-top:8px}
    .badge{display:inline-block;font-size:11px;letter-spacing:2px;text-transform:uppercase;padding:4px 12px;border:1px solid ${row.status === "issued" ? "#16a34a" : "#dc2626"};color:${row.status === "issued" ? "#16a34a" : "#dc2626"};border-radius:2px;margin-top:12px}
    .details{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:24px 0}
    .details dt{font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#888}
    .details dd{font-size:15px;margin-top:2px}
    .hash{font-family:monospace;font-size:11px;word-break:break-all;background:#f5f5f5;padding:12px;border-radius:4px;margin:24px 0}
    .hash dt{font-size:10px;text-transform:uppercase;letter-spacing:1px;color:#888;margin-bottom:4px}
    .footer{text-align:center;font-size:11px;color:#888;margin-top:32px;padding-top:16px;border-top:1px solid #ccc}
    @media print{body{border:none;padding:20px}}
  </style>
</head>
<body>
  <div class="header">
    <h1>ArtWall — Certificate of Authenticity</h1>
    <h2>${esc(row.title)}</h2>
    <div class="badge">${row.status === "issued" ? "Verified" : "Revoked"}</div>
  </div>

  <dl class="details">
    <div><dt>Artist</dt><dd>${esc(row.artist)}</dd></div>
    <div><dt>Issued</dt><dd>${issued}</dd></div>
    ${row.medium ? `<div><dt>Medium</dt><dd>${esc(row.medium)}</dd></div>` : ""}
    ${row.dimensions ? `<div><dt>Dimensions</dt><dd>${esc(row.dimensions)}</dd></div>` : ""}
    ${row.year ? `<div><dt>Year</dt><dd>${row.year}</dd></div>` : ""}
    <div><dt>Certificate ID</dt><dd style="font-family:monospace;font-size:12px">${esc(row.certId)}</dd></div>
  </dl>

  <dl class="hash">
    <dt>Metadata fingerprint (SHA-256)</dt>
    <dd>${esc(row.hash)}</dd>
  </dl>

  <p class="footer">
    Verify at artwall.in/verify/${esc(row.hash)}<br>
    This certificate was generated by ArtWall and confirms the authenticity of the above work.
  </p>
</body>
</html>`;

  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `inline; filename="COA-${row.certId}.html"`,
    },
  });
}

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
